language: node_js
node_js:
  - "stable"
dist: trusty
cache:
  directories:
    - node_modules
branches:
  only:
    - ch-ci-setup-159163741
install:
  - npm install
script: 
  - nyc --reporter=lcov npm run test